# Theme settings
doks:
    baseurl: /aks-wkshp-1
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: BoxBoat Cloud-Native Workshop
            image: false
        nav:
            - item_name: Resources
              item_url: '/resources'
    footer:
        content:
            logo:
                text: 
                image: true
            copyright: Copyright &copy; 2021. - BoxBoat <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/boxboat'
            - network_name: linkedin
              profile_url: 'https://www.linkedin.com/company/boxboat/'
    google_analytics:
        tracking_code: 
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/